name: Build and Deploy
on:
  push:
    branches:
      - main  # 當你 push 到 main 分支時觸發
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          # 這裡會自動幫你加上 /qsdemo/ 前綴，不用改 angular.json
          npx ng build --base-href /qsdemo/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/qsdemo/browser # 新版 Angular 編譯後會在 browser 資料夾
          branch: gh-pages # 這是自動生成的網頁分支